// Deterministic synthetic fixtures. No customer data or browser automation.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
global.window=global;global.document={addEventListener(){},querySelector(){return null;}};
global.requestAnimationFrame=()=>0;
global.localStorage={getItem(){return null;},setItem(){}};
for(const name of ['constants','utils','importer','geo','intelligence','autopilot','analytics','public-context','causal-context','power','director','ui','app'])vm.runInThisContext(fs.readFileSync(path.join(root,'js',name+'.js'),'utf8'),{filename:name+'.js'});
let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
AU.csv={parseFile:async f=>({rows:f.rows,parseErrors:f.issues||[]})};
AU.xlsxLite={parseFile:async f=>({rows:f.rows,sheetName:'Sheet1'})};
const file=(name,rows,issues=[])=>({name,rows,issues,size:100,lastModified:new Date(2026,8,6).getTime()});
const customer=(code,name,phone)=>({'Code client':code,'Nom prenom':name,Telephone:phone,'E-mail':'','Code postal':'63100',Ville:'Clermont-Ferrand','Adresse 1':'1 rue Test'});
const item=(code,stock)=>({'Code article':code,Designation:'Produit '+code,Stock:stock,Fournisseur:'Fournisseur test',Rayon:'LIQUIDES',Famille:'50ML','Vente TTC':20});
const sale=(id,when,ttc,qty=1,vendor='Arnaud',code='0001')=>({Date:when,'Num. vente':id,Ticket:id,'Code article':code,Designation:'Produit '+code,Quantite:qty,'Vente TTC':ttc,'Vente HT':ttc/1.2,'Achat HT':ttc/2.4,Marge:ttc/2.4,Remise:0,Vendeur:vendor,Client:'Client Test',Telephone:'0600000001',Rayon:'LIQUIDES',Famille:'50ML',Retour:qty<0?'Oui':'Non'});
const model=(c,s,k)=>AU.analytics.buildModel({clientsImport:c,salesImports:s,catalogueImport:k});
(async()=>{
 const clients=await AU.importer.parseFile('clients',file('Clients.xlsx',[customer('C1','Client Test','0600000001')]));
 const stock=await AU.importer.parseFile('catalogue',file('Catalogue.xlsx',[item('0001',2),item('0002',7),item('0003',-1)]));stock.observedAt=new Date(2026,2,31);
 const jan=await AU.importer.parseFile('ventes',file('Ventes.csv',[sale('J1','02/01/2026 10:00:00',24),sale('J2','12/01/2026 14:00:00',48,2)]));
 const feb=await AU.importer.parseFile('ventes',file('Ventes (1).csv',[sale('F1','02/02/2026 10:00:00',36,1,'Antoine'),sale('F2','12/02/2026 14:00:00',-12,-1)]));
 const before=JSON.stringify(jan),appended=AU.app.appendSales([jan],[feb]),m=model(clients,appended.datasets,stock);
 test('January + February retain four unique tickets and exact net CA',()=>{assert.equal(m.transactions.length,4);assert.equal(m.overview.caTTC,96);assert.equal(m.overview.caHT,80);assert.equal(m.overview.margin,40);});
 test('Analysis does not mutate persisted imported sales',()=>assert.equal(JSON.stringify(jan),before));
 const dup=AU.app.appendSales(appended.datasets,[jan,feb]);
 test('Repeated month imports never double sales or retain duplicate datasets',()=>{assert.equal(dup.duplicates,4);assert.equal(dup.datasets.length,2);assert.equal(model(clients,dup.datasets,stock).overview.caTTC,96);});
 const combined=await AU.importer.parseFile('ventes',file('Ventes (9).csv',[...jan.normalized.map(()=>null)].filter(Boolean).concat([sale('J1','02/01/2026 10:00:00',24),sale('J2','12/01/2026 14:00:00',48,2),sale('F1','02/02/2026 10:00:00',36,1,'Antoine'),sale('F2','12/02/2026 14:00:00',-12,-1),sale('M1','02/03/2026 10:00:00',60,3)])));
 const overlap=AU.app.appendSales(dup.datasets,[combined]);
 test('Overlapping multi-month import stores only new tickets',()=>{assert.equal(overlap.duplicates,4);assert.equal(overlap.datasets.at(-1).rowCount,1);assert.equal(model(clients,overlap.datasets,stock).overview.caTTC,156);});
 const conflict=await AU.importer.parseFile('ventes',file('Ventes.csv',[sale('J1','02/01/2026 10:00:00',25)]));
 test('Conflicting ticket amounts reject append and preserve existing ledger',()=>{assert.throws(()=>AU.app.appendSales([jan],[conflict]),/contradictoire/);assert.equal(model(clients,[jan],stock).overview.caTTC,72);});
 const vendorCorrection=await AU.importer.parseFile('ventes',file('Ventes.csv',[sale('J1','02/01/2026 10:00:00',24,1,'Antoine')]));
 test('Changing the vendor on an existing ticket is a conflict, not a silent duplicate',()=>assert.throws(()=>AU.app.appendSales([jan],[vendorCorrection]),/contradictoire/));
 test('Catalogue items without sales are retained in product analysis',()=>{assert.equal(m.products.length,3);assert.equal(m.productByCode.get('0002').stock,7);});
 const alias=await AU.importer.parseFile('ventes',file('Ventes.csv',[sale('A1','13/02/2026 12:00:00',24,1,'Arnaud','1')]));
 const aliasModel=model(clients,[jan,feb,alias],stock);
 test('Normalized product codes share one catalogue stock and one product',()=>{assert.equal(aliasModel.products.length,3);assert.equal(aliasModel.productByCode.get('1'),aliasModel.productByCode.get('0001'));assert.equal(aliasModel.productByCode.get('0001').qty,4);});
 test('Future cohort months are unknown, never zero retention',()=>{assert.equal(m.cohorts[0].retention[6].rate,null);});
 test('A return-only ticket does not count as a new customer visit',()=>{assert.equal(m.customers[0].visitCount,3);assert.equal(AU.util.dateKey(m.customers[0].lastVisit),'2026-02-02');});
 test('Net CA includes returns while purchase basket uses positive tickets',()=>{const s=AU.director.metrics(m,m.transactions);assert.equal(s.value,96);assert.equal(s.purchases,3);assert.equal(s.basket,36);assert.equal(s.returns,1);assert.equal(s.returnValue,-12);});
 const fieldsMissing=[sale('N1','04/03/2026 12:00:00',24)];delete fieldsMissing[0]['Vente HT'];delete fieldsMissing[0].Marge;
 const missing=await AU.importer.parseFile('ventes',file('Ventes.csv',fieldsMissing)),mm=model(clients,[missing],stock);
 test('Missing HT and margin stay unknown in director metrics',()=>{AU.director.setData({settings:{basis:'HT'}});const s=AU.director.metrics(mm,mm.transactions);assert.equal(s.ht,null);assert.equal(s.value,null);assert.equal(s.margin,null);});
 AU.director.setData({settings:{basis:'TTC',leadDays:5,safetyDays:2,targetDays:28},itemRules:{'0001':{pack:4,incoming:1}}});
 const recent=await AU.importer.parseFile('ventes',file('Ventes.csv',[sale('R1','25/03/2026 10:00:00',240,12),sale('R2','31/03/2026 10:00:00',40,2)]));
 const rm=model(clients,[recent],stock),order=AU.director.reorder(rm);
 test('Reorder uses 7 observed days rather than an invented 28-day history',()=>{const r=order.find(x=>x.code==='0001');assert.equal(r.observedDays,7);assert.equal(r.rate,2);assert.equal(r.pack,4);assert.equal(r.proposed,56);});
 test('Negative stock never generates an automatic order quantity',()=>{const r=order.find(x=>x.code==='0003');assert.equal(r.proposed,0);assert.equal(r.reason,'Stock à corriger');});
 test('Unsold stocked catalogue item is visible with unknown coverage',()=>{const r=order.find(x=>x.code==='0002');assert.equal(r.proposed,0);assert.equal(r.coverage,null);});
 test('Previous-period comparison uses the same weekdays',()=>{const r=AU.director.ranges(rm,'month');assert.equal(r.from.getDay(),r.previousFrom.getDay());assert.equal(r.to.getDay(),r.previousTo.getDay());assert.equal(r.comparable,false);});
 test('Annual comparator uses 52 weeks, including leap-year/calendar shifts',()=>{const r=AU.director.ranges(rm,'28','year');assert.equal(AU.util.daysBetween(r.previousFrom,r.from),364);});
 AU.director.setData({settings:{monthlyGoal:1000,openDays:[1,2,3,4,5,6],closedDates:['2026-03-30']}});
 test('Incomplete month blocks daily goal extrapolation in the view model',()=>{assert.equal(AU.director.goal(rm).complete,false);assert.equal(AU.director.goal(rm).totalDays,25);});
 const newer={...clients,observedAt:new Date(2026,2,1),normalized:[{...clients.normalized[0],name:'Nom récent'}]},older={...clients,observedAt:new Date(2026,0,1)};
 test('Old client export cannot roll back newer client details',()=>assert.equal(AU.app.mergeClients(newer,older).normalized[0].name,'Nom récent'));
 test('Historic clients absent from a newer export remain linkable',()=>{const next={...clients,observedAt:new Date(2026,3,1),normalized:[{...clients.normalized[0],codeClient:'C2'}]};assert.equal(AU.app.mergeClients(newer,next).normalized.length,2);});
 const malformed=await AU.importer.parseFile('ventes',file('Ventes.csv',[{...sale('B1','04/03/2026',24),Quantite:'erreur'}]));
 test('Malformed required numbers are blocked rather than converted to zero',()=>assert.equal(malformed.ok,false));
 const blankStock=await AU.importer.parseFile('catalogue',file('Catalogue.xlsx',[item('0001','')]));
 test('Blank stock is not a zero-stock fact',()=>assert.equal(blankStock.ok,false));
 const badCsv=await AU.importer.parseFile('ventes',file('Ventes.csv',[sale('B1','04/03/2026',24)],[{code:'TooFewFields'}]));
 test('CSV column shifts block the import',()=>assert.equal(badCsv.ok,false));
 const vendorMixed=await AU.importer.parseFile('ventes',file('Ventes.csv',[sale('B1','04/03/2026',24,1,'Arnaud'),sale('B1','04/03/2026',24,1,'Antoine')]));
 test('Mixed vendors on one ticket block ambiguous attribution',()=>assert.equal(vendorMixed.ok,false));
 test('French impossible dates and impossible hours are rejected',()=>{assert.equal(AU.util.parseTgmDate('31/02/2026'),null);assert.equal(AU.util.parseTgmDate('2026-02-31'),null);assert.equal(AU.util.parseTgmDate('01/03/2026 25:00'),null);assert.ok(AU.util.parseTgmDate('29/02/2024'));});
 test('French numbers, negative values and zero remain precise',()=>{assert.equal(AU.util.toNullableNumber('1 234,56 €'),1234.56);assert.equal(AU.util.toNullableNumber('-12,50'),-12.5);assert.equal(AU.util.toNullableNumber('abc'),null);assert.equal(AU.util.toNullableNumber('0'),0);});
 test('CSV exports neutralize spreadsheet formula injection while retaining numeric negatives',()=>{assert.ok(AU.util.toCsv([{a:'=HYPERLINK("x")',b:-12,c:'+330000'}]).includes("'=HYPERLINK"));assert.equal(AU.util.toCsv([{a:-12}]).split('\r\n')[1],'-12');});
 const backup={format:'stoom-director-backup',schema:1,imports:{clients,ventes:[jan,feb],catalogue:stock},director:AU.director.getData()};
 const restored=AU.app.parseBackup(JSON.stringify(backup));
 test('JSON backup restores Dates and reproduces the exact ledger',()=>{assert.ok(restored.imports.ventes[0].normalized[0].date instanceof Date);assert.equal(model(restored.imports.clients,restored.imports.ventes,restored.imports.catalogue).overview.caTTC,96);});
 test('Invalid backup cannot be restored',()=>{assert.throws(()=>AU.app.parseBackup('{}'),/compatible/);const b=JSON.parse(JSON.stringify(backup));b.imports.ventes[0].normalized[0].saleTTC='oops';assert.throws(()=>AU.app.parseBackup(JSON.stringify(b)),/Montant invalide/);});
 const teamRows=[];for(let i=0;i<20;i++){teamRows.push(sale('T'+i,'02/03/2026 10:00:00',24,1,'Arnaud'));teamRows.push(sale('P'+i,'02/03/2026 10:00:00',36,1,'Antoine'));}
 const team=await AU.importer.parseFile('ventes',file('Ventes.csv',teamRows)),tm=model(clients,[team],stock),rep=AU.director.vendorReport(tm,tm.transactions,'Arnaud');
 test('Vendor totals, hours and peer-weighted basket are computed from the same ledger',()=>{assert.equal(rep.summary.value,480);assert.equal(rep.hours[0].purchases,20);assert.equal(rep.matched,20);assert.equal(rep.observedBasket,24);assert.equal(rep.expectedBasket,36);});
 test('Missing hours are not presented as midnight performance',()=>{const ts=tm.transactions.map(t=>({...t,date:AU.util.startOfDay(t.date)}));assert.equal(AU.director.vendorReport(tm,ts,'Arnaud').hasHours,false);});
 // Render functions are evaluated as pure HTML emitters, without a browser.
 function fakeNode(){return {value:'',dataset:{},style:{},classList:{add(){},remove(){}},addEventListener(){},querySelector(){return fakeNode();},querySelectorAll(){return []},insertAdjacentHTML(where,text){this.innerHTML+=text;},innerHTML:''};}
 for(const view of ['today','operations','reorder','settings','salesforce','dashboard','clients','products','rayons','stock','fidelity','intelligence','alerts','context','geo','calendar','associations','compare','quality','autopilot']){
   const node=fakeNode();AU.ui.render(view,tm,node);
   test('Render '+view+' completes without a runtime error',()=>{assert.notEqual(node.dataset.viewState,'error',node.dataset.viewError);assert.ok(node.innerHTML.length>100);assert.ok(!/NaN/.test(node.innerHTML));});
 }
 // Exercise staged imports and save failure through the actual application controller.
 const nodes=new Map();document.querySelector=sel=>{if(!nodes.has(sel))nodes.set(sel,fakeNode());return nodes.get(sel);};document.querySelectorAll=()=>[];
 AU.ui.toast=()=>{};AU.storage={commitWorkspace:async()=>{throw new Error('Quota test');},saveStockSnapshot:async()=>{},listStockSnapshots:async()=>[],listAnalysisSnapshots:async()=>[],saveAnalysisSnapshot:async()=>{}};
 const state=AU.app.state;state.initializing=false;state.imports={clients,ventes:[jan],catalogue:stock};state.pending={...state.imports,ventes:[jan]};state.model=model(clients,[jan],stock);
 const savedModel=state.model;
 await AU.app.handleFiles('ventes',[file('Ventes.csv',[sale('F1','02/02/2026 10:00:00',36,1,'Antoine')])]);
 test('Selecting new sales stages them without changing the validated model',()=>{assert.equal(state.model,savedModel);assert.equal(state.imports.ventes.length,1);assert.equal(state.pending.ventes.length,2);});
 await AU.app.runAnalysis();
 test('A storage failure leaves the validated model and imports unchanged',()=>{assert.equal(state.model,savedModel);assert.equal(state.imports.ventes.length,1);assert.equal(state.analysisRunning,false);});
 document.querySelector('#catalogueObserved').value='2026-01-01';
 await AU.app.handleFiles('catalogue',[file('Catalogue.xlsx',[item('0001',99)])]);
 test('An older stock observation is staged as history without replacing current stock',()=>{assert.equal(state.pending.catalogue,stock);assert.equal(state.stagedStock.normalized[0].stock,99);});
 test('Unavailable margin remains unknown in legacy product profiles',()=>assert.equal(mm.products[0].margin,null));
 const source=fs.readFileSync(path.join(root,'js/csv.js'),'utf8').replace('return { parseFile };','return { parseFile, workerSource };');vm.runInThisContext(source);
 const messages=[],context={postMessage:m=>messages.push(m),FileReaderSync:class{readAsText(f){return f.content;}}};vm.createContext(context);vm.runInContext(AU.csv.workerSource(),context);
 context.onmessage({data:{file:{content:'Date;Designation\n01/01/2026;"Un nom; avec séparateur"\n'}}});
 test('CSV tokenizer preserves quoted separators',()=>assert.equal(messages.find(m=>m.type==='chunk').rows[0].Designation,'Un nom; avec séparateur'));
 messages.length=0;context.onmessage({data:{file:{content:'Date;Designation\n01/01/2026;"Non fermé'}}});
 test('CSV tokenizer reports unclosed quotes',()=>assert.ok(messages.find(m=>m.type==='done').issues.some(i=>i.code==='UnclosedQuote')));
 console.log(`\n${checks} director checks passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
